### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ivorbosloper** [fiboa/administrative-division-extension#1]
I would like to see a link to the definition of SO_3166-1_alpha-2, e.g. 

E.g. add to the README:

> See [https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2] for more information about SO_3166-1_alpha-2

And a more general remark, I miss an example in the README. What will the extension look like in the feature. I have to do 3 clicks to understand it. Maybe add a snippet of the json on the README?

```
{
  "fiboa": {
      "fiboa_version": "0.2.0",
      "fiboa_extensions": [
          "https://fiboa.github.io/administrative-division-extension/v0.1.0/schema.yaml"
      ]
  },
  "type": "FeatureCollection",
  "features": [
      {
          "type": "Feature",
          "properties": {
              "admin:country_code": "NL",
              "admin:subdivision_code": "UT"
          },
          "geometry": {}
   ]
}
```

**Comment by m-mohr** [comment]
Good ideas, but I linked to the official ISO sources and simplified the example to be format independant. We still have full GeoJSON and GeoParquet examples in the examples folder.
